language: r
cache: packages
r_packages:
  - data.table
  - stringr
  - taxize
  - ritis
  - covr
  - EML
r_github_packages:
  - EDIorg/EDIutils
warnings_are_errors: false
matrix:
  include:
    - os: linux
      r: devel
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libudunits2-dev
after_success:
  - Rscript -e 'library(covr); codecov()'
