language: r
cache: packages
r_packages:
  - stringr
  - taxize
  - ritis
  - readr
  - reader
  - covr
  - methods
  - EML
r_github_packages:
  - EDIorg/EDIutils
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
