language: r
cache: packages
r_packages:
  - stringr
  - taxize
  - ritis
  - readr
  - reader
  - covr
  - EML
r_github_packages:
  - EDIorg/EDIutils
warnings_are_errors: false
matrix:
  include:
    - os: linux
      r: devel
    - os: linux
      r: release
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libudunits2-dev
after_success:
  - Rscript -e 'library(covr); codecov()'
